### ISSUE TITLE
Add dashboard url to environment classes

### ISSUE THREAD

**Issue by LucDelmonRailsE** [checkout/checkout-sdk-ruby#119]
### Description
The environment in
https://github.com/checkout/checkout-sdk-ruby/blob/master/lib/checkout_sdk/environment.rb

exposes a list of useful url.

Yet they do not contain the dashboard url such as
`https://dashboard.sandbox.checkout.com/`
This could be useful to use when creating dynamic link to payment for admin interfaces. I am now relying on an hardcoded solution that will be broken if you decide to change URL.

This could be really easy to propose in a PR but I wanted to check with you that the concept is ok for you ? Maybe this is over extending the purpose of this class.

## Proposed Solution
Add the dashboard url to environment classes

- [ ] I may be able to implement this feature

**Comment by armando-ibarra-cko** [comment]
Hello @LucDelmonRailsE 

Sorry for the late on the response.
The thing is that the SDK is meant to be the interface between the API's and the clients, from my perspective dashboard is another interface itself, internally is uses other versions of the API that does not necessarily relate to the ones used by the SDKs. Also these URLs will not be used on the SDK which probably adds some confusion about why they are present there.

**Comment by LucDelmonRailsE** [comment]
Ok I see. I will keep it like this then. Thanks for the answer

**Comment by armando-ibarra-cko** [comment]
If you need any help or face any issue, please let us know
