### ISSUE TITLE
Rubygems

### ISSUE THREAD

**Issue by mkcosta** [checkout/checkout-sdk-ruby#33]
Hi, can you please push the latest version, 0.2.2, to rubygems?
Thanks

**Comment by Armando-Ibarra** [comment]
Hi @mkcosta 

Sorry to circle back too late on this, but we just released a new version for Ruby SDK
https://github.com/checkout/checkout-sdk-ruby/releases/tag/1.0.0

Which includes a lot of new functionalities for previous and default version, you can see the README for more details.

Let us know if you have any issue.

**Comment by mkcosta** [comment]
The new gem depends on `faraday >= 2` which essentially breaks all of the other external dependencies. 
You should relax your gem dependencies (faraday is just an Net/HTTP wrapper), otherwise using `checkout_sdk` becomes pretty impossible for us.
