### ISSUE TITLE
Can't get recommendation_code from payment details

### ISSUE THREAD

**Issue by quangvinh-fetchtech** [checkout/checkout-sdk-ruby#36]
Could you please help i can't get recommendation_code?
Anyone suggest me how to get it?
https://docs.checkout.com/resources/codes/recommendation-codes

**Comment by Armando-Ibarra** [comment]
Hi @quangvinh-fetchtech 

Sorry to circle back too late on this, but we just released a new version for Ruby SDK
https://github.com/checkout/checkout-sdk-ruby/releases/tag/1.0.0

Which includes a lot of new functionalities for previous and default version, you can see the README for more details.

The payment response should have this field `recommendation_code` which tell you the codes that you previosly shared, please let us know if you have any issue.
