### ISSUE TITLE
Some 3DS fields not supported

### ISSUE THREAD

**Issue by mattgibson** [checkout/checkout-sdk-ruby#49]
I'd like to set the 3DS `challenge_indicator` field, but it seems not to be present anywhere in the gem code. Could this be added please?

https://api-reference.checkout.com/#operation/requestAPaymentOrPayout!path=0/3ds/challenge_indicator&t=request

**Comment by Armando-Ibarra** [comment]
Hi @mattgibson 

Sorry to circle back too late on this, but we just released a new version for Ruby SDK
https://github.com/checkout/checkout-sdk-ruby/releases/tag/1.0.0

Which includes a lot of new functionalities for previous and default version, you can see the README for more details.

Including the latest 3DS fields, let us know if you have any issues.
