### ISSUE TITLE
Hosted payment support

### ISSUE THREAD

**Issue by pradosh987** [checkout/checkout-sdk-ruby#52]
Does this gem support hosted payment resource? Couldn't find anything in code.

**Comment by Armando-Ibarra** [comment]
Hi @pradosh987 

Sorry to circle back too late on this, but we just released a new version for Ruby SDK
https://github.com/checkout/checkout-sdk-ruby/releases/tag/1.0.0

Which includes a lot of new functionalities for previous and default version, you can see the README for more details.

Including Hosted Payments and Payments Links, let us know if you have any issue or question.
