### ISSUE TITLE
Set proxy on new connection

### ISSUE THREAD

**Issue by nipunhsud** [checkout/checkout-sdk-ruby#54]
We are using VGS with checkout which requires us to set VGS forward proxy to unmask credit card data. It does not look like there is an option to configure a proxy when instantiating a connection.

**Comment by Armando-Ibarra** [comment]
Hi @nipunhsud 

Sorry to circle back too late on this, but we just released a new version for Ruby SDK
https://github.com/checkout/checkout-sdk-ruby/releases/tag/1.0.0

Which includes a lot of new functionalities for previous and default version, you can see the README for more details.

This version includes a way to provide your own http client or custom API environment if you want to set some proxy, let us know if you're facing any issue.
