### ISSUE TITLE
Connection remains open

### ISSUE THREAD

**Issue by einzige** [checkout/checkout-sdk-ruby#7]
Unless you open the source code, you cant' realize why it doesn't disconnect.

https://github.com/checkout/checkout-sdk-ruby/blob/bc78320ce92284bd95df47f25fbe5c7f3e784611/lib/checkout_sdk/api_resource.rb#L8

If you really want to have persisted connection, provide it as a constructor argument or make it passing through a block.

If somebody makes many requests using your README, they may really open too many connections.

**Comment by nicolas-maalouf-cko** [comment]
Hi @einzige thanks for your feedback

Is this some improvement you'd be happy to open a pull request for?

Thanks

**Comment by einzige** [comment]
Hi @nicolas-maalouf-cko 

I'll submit a couple of updates, would be nice to have this repo as well as the API itself more or less full and organized.

**Comment by nicolas-maalouf-cko** [comment]
Thanks @einzige !
Are you using it for a particular integration?

**Comment by einzige** [comment]
Yep, we launched the production and having some issues, I'll create a separate ticket for that

**Comment by einzige** [comment]
Tested updates on production, will submit here soon.

**Comment by Armando-Ibarra** [comment]
Hi @einzige 

Sorry to circle back too late on this, but we just released a new version for Ruby SDK
https://github.com/checkout/checkout-sdk-ruby/releases/tag/1.0.0

Which includes a lot of new functionalities for previous and default version, you can see the README for more details.
