### ISSUE TITLE
Read timeout

### ISSUE THREAD

**Issue by einzige** [checkout/checkout-sdk-ruby#8]
Receiving `#2071 Excon::Error::Timeout: read timeout reached` while making a regular authroize payment operation. 

The default timeout for Excon is 60 seconds. No jokes, 60!

It waits for 60 seconds in live mode and fails to receive a response. 
That basically means that something is off on the Checkout API COM server end (possibly).

Action items could be:

- [ ] Reduce the read timeout in this lib config (actually provide a setting)
- [ ] Eliminate the issue on the server side for LIVE and SANDBOX modes (it happens in both environments occasionally) 

Thanks

**Comment by nicolas-maalouf-cko** [comment]
@einzige Checkout.com's gateway API's official timeout is 60s.
Reducing the SDK's timeout may incur successful authorisations to be seen as failed.

Can you please send sample requests for which authorisations took > 5s to process to support@checkout.com ?

**Comment by einzige** [comment]
Thanks, they provided access to Freshdesk. 
Settings are still required, majority of client apps won't be happy to hang for 60 seconds anyway.

**Comment by Armando-Ibarra** [comment]
Hi @einzige 

Sorry to circle back too late on this, but we just released a new version for Ruby SDK
https://github.com/checkout/checkout-sdk-ruby/releases/tag/1.0.0

Which includes a lot of new functionalities for previous and default version, you can see the README for more details.

Including a way to provide your own http client with custom time out, let us know if you have any issue.
